name: ridebuddies
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_screenutil: ^3.2.0
  font_awesome_flutter: ^8.10.0
  google_maps_flutter: ^1.0.5
  flutter_svg: ^0.19.1
  material_design_icons_flutter: ^4.0.5755
  geolocator: ^6.1.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/map_style/

  # example:
  fonts:
    - family: Handel Gothic
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

